/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface VaultInterface extends ethers.utils.Interface {
  functions: {
    "addPendingMember(address)": FunctionFragment;
    "getOwnEncryptedPrivateKey()": FunctionFragment;
    "getOwnSecretIds()": FunctionFragment;
    "getPublicKey(address)": FunctionFragment;
    "getSecret(uint256)": FunctionFragment;
    "isMember(address)": FunctionFragment;
    "joinVault(string,string)": FunctionFragment;
    "members(address)": FunctionFragment;
    "pendingMembers(address)": FunctionFragment;
    "secretExists(uint256)": FunctionFragment;
    "secrets(uint256)": FunctionFragment;
    "storeSecret(string,string,string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addPendingMember",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getOwnEncryptedPrivateKey",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOwnSecretIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPublicKey",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getSecret",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "isMember", values: [string]): string;
  encodeFunctionData(
    functionFragment: "joinVault",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "members", values: [string]): string;
  encodeFunctionData(
    functionFragment: "pendingMembers",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "secretExists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "secrets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "storeSecret",
    values: [string, string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "addPendingMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOwnEncryptedPrivateKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOwnSecretIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPublicKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSecret", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isMember", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "joinVault", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "members", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingMembers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "secretExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "secrets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "storeSecret",
    data: BytesLike
  ): Result;

  events: {
    "SecretCreated(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "SecretCreated"): EventFragment;
}

export type SecretCreatedEvent = TypedEvent<
  [string, BigNumber] & { member: string; secretId: BigNumber }
>;

export class Vault extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: VaultInterface;

  functions: {
    addPendingMember(
      addr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getOwnEncryptedPrivateKey(overrides?: CallOverrides): Promise<[string]>;

    getOwnSecretIds(overrides?: CallOverrides): Promise<[BigNumber[]]>;

    getPublicKey(addr: string, overrides?: CallOverrides): Promise<[string]>;

    getSecret(
      secretId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        [string, string, string] & {
          publicLabel: string;
          encryptedUsername: string;
          encryptedPassword: string;
        }
      ]
    >;

    isMember(addr: string, overrides?: CallOverrides): Promise<[boolean]>;

    joinVault(
      encryptedPrivateKey: string,
      publicKey: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    members(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [string, string] & { encryptedPrivateKey: string; publicKey: string }
    >;

    pendingMembers(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    secretExists(
      secretId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    secrets(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string] & {
        publicLabel: string;
        encryptedUsername: string;
        encryptedPassword: string;
      }
    >;

    storeSecret(
      publicLabel: string,
      encryptedUsername: string,
      encryptedPassword: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  addPendingMember(
    addr: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getOwnEncryptedPrivateKey(overrides?: CallOverrides): Promise<string>;

  getOwnSecretIds(overrides?: CallOverrides): Promise<BigNumber[]>;

  getPublicKey(addr: string, overrides?: CallOverrides): Promise<string>;

  getSecret(
    secretId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, string, string] & {
      publicLabel: string;
      encryptedUsername: string;
      encryptedPassword: string;
    }
  >;

  isMember(addr: string, overrides?: CallOverrides): Promise<boolean>;

  joinVault(
    encryptedPrivateKey: string,
    publicKey: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  members(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [string, string] & { encryptedPrivateKey: string; publicKey: string }
  >;

  pendingMembers(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  secretExists(
    secretId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  secrets(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, string, string] & {
      publicLabel: string;
      encryptedUsername: string;
      encryptedPassword: string;
    }
  >;

  storeSecret(
    publicLabel: string,
    encryptedUsername: string,
    encryptedPassword: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addPendingMember(addr: string, overrides?: CallOverrides): Promise<void>;

    getOwnEncryptedPrivateKey(overrides?: CallOverrides): Promise<string>;

    getOwnSecretIds(overrides?: CallOverrides): Promise<BigNumber[]>;

    getPublicKey(addr: string, overrides?: CallOverrides): Promise<string>;

    getSecret(
      secretId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string] & {
        publicLabel: string;
        encryptedUsername: string;
        encryptedPassword: string;
      }
    >;

    isMember(addr: string, overrides?: CallOverrides): Promise<boolean>;

    joinVault(
      encryptedPrivateKey: string,
      publicKey: string,
      overrides?: CallOverrides
    ): Promise<void>;

    members(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [string, string] & { encryptedPrivateKey: string; publicKey: string }
    >;

    pendingMembers(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    secretExists(
      secretId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    secrets(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string] & {
        publicLabel: string;
        encryptedUsername: string;
        encryptedPassword: string;
      }
    >;

    storeSecret(
      publicLabel: string,
      encryptedUsername: string,
      encryptedPassword: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "SecretCreated(address,uint256)"(
      member?: null,
      secretId?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { member: string; secretId: BigNumber }
    >;

    SecretCreated(
      member?: null,
      secretId?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { member: string; secretId: BigNumber }
    >;
  };

  estimateGas: {
    addPendingMember(
      addr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getOwnEncryptedPrivateKey(overrides?: CallOverrides): Promise<BigNumber>;

    getOwnSecretIds(overrides?: CallOverrides): Promise<BigNumber>;

    getPublicKey(addr: string, overrides?: CallOverrides): Promise<BigNumber>;

    getSecret(
      secretId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isMember(addr: string, overrides?: CallOverrides): Promise<BigNumber>;

    joinVault(
      encryptedPrivateKey: string,
      publicKey: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    members(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    pendingMembers(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    secretExists(
      secretId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    secrets(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    storeSecret(
      publicLabel: string,
      encryptedUsername: string,
      encryptedPassword: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addPendingMember(
      addr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getOwnEncryptedPrivateKey(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getOwnSecretIds(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getPublicKey(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSecret(
      secretId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isMember(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    joinVault(
      encryptedPrivateKey: string,
      publicKey: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    members(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pendingMembers(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    secretExists(
      secretId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    secrets(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    storeSecret(
      publicLabel: string,
      encryptedUsername: string,
      encryptedPassword: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
